version: "2"
services:
  ycloud:
    image: openjdk:17-ea-oraclelinux7
    container_name: ycloud
    ports:
      - "8080:8999"
    command: bash -c "java '-Dloader.path=/home/cloud/lib' -jar /home/cloud/cloud-front-1.0.jar"
    volumes:
      - $PWD:/home/cloud
    environment:
      - TZ=Asia/shanghai
      - PASSWORD=xiaoyang #optional
    # restart: unless-stopped
    restart: always