web:
  html:
    name: YCloud-云盘
    title: YCloud-云盘
    footer: Copyright @2022 YCloud

oauth:
  qq:
    appid: 101870409
    appkey: 2d16bf76ddc04d893bc6b69673ec66c7
    callback: http://127.0.0.1:8999/oauth/callback/qq

ycloud:
  local:
    root: /local
